name: Submit Dependencies
on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # Weekly

jobs:
  submit-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for dependency submission
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: jessehouwing/actions-dependency-submission@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/dependency-review-action@v4.8.2
        if: ${{ github.event_name == 'pull_request' }}
        with:
          retry-on-snapshot-warnings: true
      - uses: actions/download-artifact@f44cd7b40bfd40b6aa1cc1b9b5b7bf03d3c67110
        if: false
      - uses: actions/download-artifact@4.0.0
        if: false
